FROM node:21-alpine

ARG APP=/usr/src/app
ARG CACHE=/usr/src/cache

ENV NODE_ENV=
ENV TOKEN=
ENV FACEIT_TOKEN=
ENV STEAM_TOKEN=
ENV TOPGG_TOKEN=

RUN apk update && \
  apk add --no-cache \
  build-base \
  cairo-dev \
  pango-dev \
  jpeg-dev \
  giflib-dev \
  librsvg-dev


WORKDIR $CACHE
COPY package.json .
# COPY yarn.lock .

RUN yarn install

WORKDIR $APP

CMD ["yarn", "dev"]